version: '3.8'

services:
  backend: 
    container_name: tasknest-backend-app
    image: tasknest-backend-app:latest
    build: 
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/projects:/var/www/html
      - ../backend/.env:/var/www/html/.env
    expose:
      - "9000"
  nginx:
    container_name: tasknest-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../backend/projects:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  frontend:
    container_name: tasknest-frontend-app
    image: tasknest-frontend-app:latest
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    volumes: 
      - ../frontend:/app
      - /app/node_modules
    env_file:
      - ../frontend/.env
    command: npm run dev -- --host
    tty: true
    stdin_open: true
  rabbitmq:
    container_name: tasknest-rabbitmq
    image: rabbitmq:3-management
    build: 
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: tasknestadmin
      RABBITMQ_DEFAULT_PASS: controlroom